# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.4.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_vps import schemas  # noqa: F401


class ConfiguratorMemorySettings(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def range() -> typing.Type['ConfiguratorRange']:
                return ConfiguratorRange
        
            @staticmethod
            def available_range() -> typing.Type['ConfiguratorRange']:
                return ConfiguratorRange
            step = schemas.IntSchema
            __annotations__ = {
                "range": range,
                "available_range": available_range,
                "step": step,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["range"]) -> 'ConfiguratorRange': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["available_range"]) -> 'ConfiguratorRange': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["step"]) -> MetaOapg.properties.step: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["range", "available_range", "step", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["range"]) -> typing.Union['ConfiguratorRange', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["available_range"]) -> typing.Union['ConfiguratorRange', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["step"]) -> typing.Union[MetaOapg.properties.step, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["range", "available_range", "step", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        range: typing.Union['ConfiguratorRange', schemas.Unset] = schemas.unset,
        available_range: typing.Union['ConfiguratorRange', schemas.Unset] = schemas.unset,
        step: typing.Union[MetaOapg.properties.step, decimal.Decimal, int, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ConfiguratorMemorySettings':
        return super().__new__(
            cls,
            *args,
            range=range,
            available_range=available_range,
            step=step,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_vps.model.configurator_range import ConfiguratorRange
