# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.8.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_vps import schemas  # noqa: F401


class ManagePrivateInterface(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            network_id = schemas.StrSchema
            allocate_new = schemas.DictSchema
        
            @staticmethod
            def specific() -> typing.Type['ManagePrivateInterfaceAllocateSpecificPrivateIp']:
                return ManagePrivateInterfaceAllocateSpecificPrivateIp
            __annotations__ = {
                "network_id": network_id,
                "allocate_new": allocate_new,
                "specific": specific,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["network_id"]) -> MetaOapg.properties.network_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["allocate_new"]) -> MetaOapg.properties.allocate_new: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["specific"]) -> 'ManagePrivateInterfaceAllocateSpecificPrivateIp': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["network_id", "allocate_new", "specific", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["network_id"]) -> typing.Union[MetaOapg.properties.network_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["allocate_new"]) -> typing.Union[MetaOapg.properties.allocate_new, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["specific"]) -> typing.Union['ManagePrivateInterfaceAllocateSpecificPrivateIp', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["network_id", "allocate_new", "specific", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        network_id: typing.Union[MetaOapg.properties.network_id, str, schemas.Unset] = schemas.unset,
        allocate_new: typing.Union[MetaOapg.properties.allocate_new, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        specific: typing.Union['ManagePrivateInterfaceAllocateSpecificPrivateIp', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ManagePrivateInterface':
        return super().__new__(
            cls,
            *_args,
            network_id=network_id,
            allocate_new=allocate_new,
            specific=specific,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_vps.model.manage_private_interface_allocate_specific_private_ip import ManagePrivateInterfaceAllocateSpecificPrivateIp
