# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.9
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_vps import schemas  # noqa: F401


class NetworkOrderIpAddressResponse(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            ip_address = schemas.StrSchema
        
            @staticmethod
            def error() -> typing.Type['NetworkOrderIpAddressResponseError']:
                return NetworkOrderIpAddressResponseError
        
            @staticmethod
            def additional_ip() -> typing.Type['StructuresAdditionalIpInfo']:
                return StructuresAdditionalIpInfo
        
            @staticmethod
            def error_v2() -> typing.Type['NetworkOrderIpAddressResponseError']:
                return NetworkOrderIpAddressResponseError
            __annotations__ = {
                "ip_address": ip_address,
                "error": error,
                "additional_ip": additional_ip,
                "error_v2": error_v2,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["ip_address"]) -> MetaOapg.properties.ip_address: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error"]) -> 'NetworkOrderIpAddressResponseError': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["additional_ip"]) -> 'StructuresAdditionalIpInfo': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["error_v2"]) -> 'NetworkOrderIpAddressResponseError': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["ip_address", "error", "additional_ip", "error_v2", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["ip_address"]) -> typing.Union[MetaOapg.properties.ip_address, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error"]) -> typing.Union['NetworkOrderIpAddressResponseError', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["additional_ip"]) -> typing.Union['StructuresAdditionalIpInfo', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["error_v2"]) -> typing.Union['NetworkOrderIpAddressResponseError', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["ip_address", "error", "additional_ip", "error_v2", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        ip_address: typing.Union[MetaOapg.properties.ip_address, str, schemas.Unset] = schemas.unset,
        error: typing.Union['NetworkOrderIpAddressResponseError', schemas.Unset] = schemas.unset,
        additional_ip: typing.Union['StructuresAdditionalIpInfo', schemas.Unset] = schemas.unset,
        error_v2: typing.Union['NetworkOrderIpAddressResponseError', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'NetworkOrderIpAddressResponse':
        return super().__new__(
            cls,
            *_args,
            ip_address=ip_address,
            error=error,
            additional_ip=additional_ip,
            error_v2=error_v2,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_vps.model.network_order_ip_address_response_error import NetworkOrderIpAddressResponseError
from beget_openapi_vps.model.structures_additional_ip_info import StructuresAdditionalIpInfo
