# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_vps import schemas  # noqa: F401


class SoftwareLicenseChangeLicensePlanResponseError(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            
            
            class code(
                schemas.EnumBase,
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    format = 'enum'
                    enum_value_to_name = {
                        "INTERNAL_ERROR": "INTERNAL_ERROR",
                        "INSUFFICIENT_FUNDS": "INSUFFICIENT_FUNDS",
                        "SERVICE_DISABLED": "SERVICE_DISABLED",
                    }
                
                @schemas.classproperty
                def INTERNAL_ERROR(cls):
                    return cls("INTERNAL_ERROR")
                
                @schemas.classproperty
                def INSUFFICIENT_FUNDS(cls):
                    return cls("INSUFFICIENT_FUNDS")
                
                @schemas.classproperty
                def SERVICE_DISABLED(cls):
                    return cls("SERVICE_DISABLED")
            message = schemas.StrSchema
        
            @staticmethod
            def insufficient_funds_error() -> typing.Type['SoftwareLicenseChangeLicensePlanResponseErrorInsufficientFundsError']:
                return SoftwareLicenseChangeLicensePlanResponseErrorInsufficientFundsError
            __annotations__ = {
                "code": code,
                "message": message,
                "insufficient_funds_error": insufficient_funds_error,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["code"]) -> MetaOapg.properties.code: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message"]) -> MetaOapg.properties.message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["insufficient_funds_error"]) -> 'SoftwareLicenseChangeLicensePlanResponseErrorInsufficientFundsError': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["code", "message", "insufficient_funds_error", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["code"]) -> typing.Union[MetaOapg.properties.code, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message"]) -> typing.Union[MetaOapg.properties.message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["insufficient_funds_error"]) -> typing.Union['SoftwareLicenseChangeLicensePlanResponseErrorInsufficientFundsError', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["code", "message", "insufficient_funds_error", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        code: typing.Union[MetaOapg.properties.code, str, schemas.Unset] = schemas.unset,
        message: typing.Union[MetaOapg.properties.message, str, schemas.Unset] = schemas.unset,
        insufficient_funds_error: typing.Union['SoftwareLicenseChangeLicensePlanResponseErrorInsufficientFundsError', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SoftwareLicenseChangeLicensePlanResponseError':
        return super().__new__(
            cls,
            *args,
            code=code,
            message=message,
            insufficient_funds_error=insufficient_funds_error,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_vps.model.software_license_change_license_plan_response_error_insufficient_funds_error import SoftwareLicenseChangeLicensePlanResponseErrorInsufficientFundsError
