# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.7
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from beget_openapi_vps import schemas  # noqa: F401


class StructuresSoftwareLicenseBillingType(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def daily() -> typing.Type['StructuresSoftwareLicenseBillingTypeDaily']:
                return StructuresSoftwareLicenseBillingTypeDaily
        
            @staticmethod
            def monthly() -> typing.Type['StructuresSoftwareLicenseBillingTypeMonthly']:
                return StructuresSoftwareLicenseBillingTypeMonthly
            __annotations__ = {
                "daily": daily,
                "monthly": monthly,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["daily"]) -> 'StructuresSoftwareLicenseBillingTypeDaily': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["monthly"]) -> 'StructuresSoftwareLicenseBillingTypeMonthly': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["daily", "monthly", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["daily"]) -> typing.Union['StructuresSoftwareLicenseBillingTypeDaily', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["monthly"]) -> typing.Union['StructuresSoftwareLicenseBillingTypeMonthly', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["daily", "monthly", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        daily: typing.Union['StructuresSoftwareLicenseBillingTypeDaily', schemas.Unset] = schemas.unset,
        monthly: typing.Union['StructuresSoftwareLicenseBillingTypeMonthly', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'StructuresSoftwareLicenseBillingType':
        return super().__new__(
            cls,
            *args,
            daily=daily,
            monthly=monthly,
            _configuration=_configuration,
            **kwargs,
        )

from beget_openapi_vps.model.structures_software_license_billing_type_daily import StructuresSoftwareLicenseBillingTypeDaily
from beget_openapi_vps.model.structures_software_license_billing_type_monthly import StructuresSoftwareLicenseBillingTypeMonthly
