# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from beget_openapi_vps.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    V1_VPS_ARCHIVE_ID = "/v1/vps/archive/{id}"
    V1_VPS_BACKUP = "/v1/vps/backup"
    V1_VPS_BACKUP_ORDERS = "/v1/vps/backup/orders"
    V1_VPS_CONFIGURATION = "/v1/vps/configuration"
    V1_VPS_CONFIGURATOR_CALCULATION = "/v1/vps/configurator/calculation"
    V1_VPS_CONFIGURATOR_INFO = "/v1/vps/configurator/info"
    V1_VPS_MARKETPLACE_SOFTWARE_LIST = "/v1/vps/marketplace/software/list"
    V1_VPS_MARKETPLACE_SOFTWARE_NAME_VERSION = "/v1/vps/marketplace/software/{name}/{version}"
    V1_VPS_NETWORK = "/v1/vps/network"
    V1_VPS_NETWORK_DETACH_IP_ADDRESS = "/v1/vps/network/detach/{ip_address}"
    V1_VPS_NETWORK_IP_ADDRESS = "/v1/vps/network/{ip_address}"
    V1_VPS_PRIVATENETWORK = "/v1/vps/private-network"
    V1_VPS_PRIVATENETWORK_NETWORK_ID = "/v1/vps/private-network/{network_id}"
    V1_VPS_PRIVATENETWORK_NETWORK_ID_SUGGESTEDADDRESS = "/v1/vps/private-network/{network_id}/suggested-address"
    V1_VPS_REGION = "/v1/vps/region"
    V1_VPS_SERVER = "/v1/vps/server"
    V1_VPS_SERVER_LIST = "/v1/vps/server/list"
    V1_VPS_SERVER_STATUSES = "/v1/vps/server/statuses"
    V1_VPS_SERVER_ID = "/v1/vps/server/{id}"
    V1_VPS_SERVER_ID_CONFIGURATION = "/v1/vps/server/{id}/configuration"
    V1_VPS_SERVER_ID_INFO = "/v1/vps/server/{id}/info"
    V1_VPS_SERVER_ID_PIN = "/v1/vps/server/{id}/pin"
    V1_VPS_SERVER_ID_PROJECT = "/v1/vps/server/{id}/project"
    V1_VPS_SERVER_ID_REBOOT = "/v1/vps/server/{id}/reboot"
    V1_VPS_SERVER_ID_REINSTALL = "/v1/vps/server/{id}/reinstall"
    V1_VPS_SERVER_ID_REMOVE = "/v1/vps/server/{id}/remove"
    V1_VPS_SERVER_ID_RESCUE = "/v1/vps/server/{id}/rescue"
    V1_VPS_SERVER_ID_RESET = "/v1/vps/server/{id}/reset"
    V1_VPS_SERVER_ID_START = "/v1/vps/server/{id}/start"
    V1_VPS_SERVER_ID_STOP = "/v1/vps/server/{id}/stop"
    V1_VPS_SNAPSHOT = "/v1/vps/snapshot"
    V1_VPS_SNAPSHOT_CALCULATOR = "/v1/vps/snapshot/calculator"
    V1_VPS_SNAPSHOT_RESTORE = "/v1/vps/snapshot/restore"
    V1_VPS_SNAPSHOT_ID = "/v1/vps/snapshot/{id}"
    V1_VPS_SNAPSHOT_ID_RESTORE = "/v1/vps/snapshot/{id}/restore"
    V1_VPS_SOFTWARE_LICENSE = "/v1/vps/software/license"
    V1_VPS_SOFTWARE_LICENSE_VPS_ID = "/v1/vps/software/license/{vps_id}"
    V1_VPS_SOFTWARE_REQUIREMENTS = "/v1/vps/software/requirements"
    V1_VPS_SSH_KEY = "/v1/vps/sshKey"
    V1_VPS_SSH_KEY_ID = "/v1/vps/sshKey/{id}"
    V1_VPS_STATISTIC_CPUDETAILS_ID = "/v1/vps/statistic/cpu-details/{id}"
    V1_VPS_STATISTIC_CPU_ID = "/v1/vps/statistic/cpu/{id}"
    V1_VPS_STATISTIC_DISKUSAGE_ID = "/v1/vps/statistic/disk-usage/{id}"
    V1_VPS_STATISTIC_DISK_ID = "/v1/vps/statistic/disk/{id}"
    V1_VPS_STATISTIC_LOADAVERAGE_ID = "/v1/vps/statistic/load-average/{id}"
    V1_VPS_STATISTIC_MEMORY_ID = "/v1/vps/statistic/memory/{id}"
    V1_VPS_STATISTIC_NETWORK_ID = "/v1/vps/statistic/network/{id}"
    V1_VPS_STATISTIC_PROCESSES_ID = "/v1/vps/statistic/processes/{id}"
    V1_VPS_SUBDOMAIN_RESERVE = "/v1/vps/subdomain/reserve"
    V1_VPS_ID_BACKUP_COPY_ID = "/v1/vps/{id}/backup/{copy_id}"
    V1_VPS_ID_BACKUP_COPY_ID_FILE = "/v1/vps/{id}/backup/{copy_id}/file"
    V1_VPS_ID_BACKUP_COPY_ID_SERVER = "/v1/vps/{id}/backup/{copy_id}/server"
    V1_VPS_ID_FM = "/v1/vps/{id}/fm"
    V1_VPS_ID_HISTORY = "/v1/vps/{id}/history"
    V1_VPS_ID_NETWORK_IP_ADDRESS = "/v1/vps/{id}/network/{ip_address}"
    V1_VPS_ID_PASSWORD = "/v1/vps/{id}/password"
    V1_VPS_ID_PRIVATENETWORK_NETWORK_ID = "/v1/vps/{id}/private-network/{network_id}"
    V1_VPS_ID_SOFTWARE = "/v1/vps/{id}/software"
    V1_VPS_ID_SOFTWARE_POSTINSTALLALERT = "/v1/vps/{id}/software/post-install-alert"
    V1_VPS_ID_SSH_ACCESS = "/v1/vps/{id}/ssh/access"
    V1_VPS_ID_SSH_KEY_SSH_KEY_ID = "/v1/vps/{id}/sshKey/{ssh_key_id}"
