# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps
from beget_openapi_vps.model.configurator_configurator_settings import ConfiguratorConfiguratorSettings
from beget_openapi_vps import configuration


class TestConfiguratorConfiguratorSettings(unittest.TestCase):
    """ConfiguratorConfiguratorSettings unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
