# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps
from beget_openapi_vps.model.network_remove_ip_address_response import NetworkRemoveIpAddressResponse
from beget_openapi_vps import configuration


class TestNetworkRemoveIpAddressResponse(unittest.TestCase):
    """NetworkRemoveIpAddressResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
