# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps
from beget_openapi_vps.model.manage_check_software_requirements_response import ManageCheckSoftwareRequirementsResponse
from beget_openapi_vps import configuration


class TestManageCheckSoftwareRequirementsResponse(unittest.TestCase):
    """ManageCheckSoftwareRequirementsResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
