# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps
from beget_openapi_vps.model.manage_attach_to_private_network_request import ManageAttachToPrivateNetworkRequest
from beget_openapi_vps import configuration


class TestManageAttachToPrivateNetworkRequest(unittest.TestCase):
    """ManageAttachToPrivateNetworkRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
