# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps
from beget_openapi_vps.model.structures_additional_ip_info import StructuresAdditionalIpInfo
from beget_openapi_vps import configuration


class TestStructuresAdditionalIpInfo(unittest.TestCase):
    """StructuresAdditionalIpInfo unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
