# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.7
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps
from beget_openapi_vps.model.network_remove_private_network_response_error_vps_network_use_error import NetworkRemovePrivateNetworkResponseErrorVpsNetworkUseError
from beget_openapi_vps import configuration


class TestNetworkRemovePrivateNetworkResponseErrorVpsNetworkUseError(unittest.TestCase):
    """NetworkRemovePrivateNetworkResponseErrorVpsNetworkUseError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
