# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.3
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps
from beget_openapi_vps.model.manage_create_vps_response_error_insufficient_funds_error import ManageCreateVpsResponseErrorInsufficientFundsError
from beget_openapi_vps import configuration


class TestManageCreateVpsResponseErrorInsufficientFundsError(unittest.TestCase):
    """ManageCreateVpsResponseErrorInsufficientFundsError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
