# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.6
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps
from beget_openapi_vps.model.network_order_ip_address_request import NetworkOrderIpAddressRequest
from beget_openapi_vps import configuration


class TestNetworkOrderIpAddressRequest(unittest.TestCase):
    """NetworkOrderIpAddressRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
