# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.5.1
    Generated by: https://openapi-generator.tech
"""

import unittest

import beget_openapi_vps
from beget_openapi_vps.model.manage_reinstall_response_error_software_variable_error import ManageReinstallResponseErrorSoftwareVariableError
from beget_openapi_vps import configuration


class TestManageReinstallResponseErrorSoftwareVariableError(unittest.TestCase):
    """ManageReinstallResponseErrorSoftwareVariableError unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
