# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.3.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_vps.paths.v1_vps_backup.get import BackupServiceGetAvailableCopies
from beget_openapi_vps.paths.v1_vps_id_backup_copy_id.get import BackupServiceGetBackupFileList
from beget_openapi_vps.paths.v1_vps_backup_orders.get import BackupServiceGetOrders
from beget_openapi_vps.paths.v1_vps_id_backup_copy_id_file.post import BackupServiceRestoreFile
from beget_openapi_vps.paths.v1_vps_id_backup_copy_id_server.post import BackupServiceRestoreServer


class BackupServiceApi(
    BackupServiceGetAvailableCopies,
    BackupServiceGetBackupFileList,
    BackupServiceGetOrders,
    BackupServiceRestoreFile,
    BackupServiceRestoreServer,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
