# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_vps.paths.v1_vps_configurator_calculation.get import ConfiguratorServiceGetCalculation
from beget_openapi_vps.paths.v1_vps_configurator_info.get import ConfiguratorServiceGetConfiguratorInfo


class ConfiguratorServiceApi(
    ConfiguratorServiceGetCalculation,
    ConfiguratorServiceGetConfiguratorInfo,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
