# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_vps.paths.v1_vps_marketplace_software_name_version.get import MarketplaceServiceGetSoftwareInfo
from beget_openapi_vps.paths.v1_vps_marketplace_software_list.get import MarketplaceServiceGetSoftwareList


class MarketplaceServiceApi(
    MarketplaceServiceGetSoftwareInfo,
    MarketplaceServiceGetSoftwareList,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
