# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.1
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_vps.paths.v1_vps_private_network.post import NetworkServiceCreatePrivateNetwork
from beget_openapi_vps.paths.v1_vps_network.get import NetworkServiceGetNetworkInfo
from beget_openapi_vps.paths.v1_vps_network.post import NetworkServiceOrderIpAddress
from beget_openapi_vps.paths.v1_vps_network_ip_address.delete import NetworkServiceRemoveIpAddress
from beget_openapi_vps.paths.v1_vps_private_network_network_id_suggested_address.post import NetworkServiceSuggestPrivateAddress


class NetworkServiceApi(
    NetworkServiceCreatePrivateNetwork,
    NetworkServiceGetNetworkInfo,
    NetworkServiceOrderIpAddress,
    NetworkServiceRemoveIpAddress,
    NetworkServiceSuggestPrivateAddress,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
