# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.9
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_vps.paths.v1_vps_software_license_vps_id.patch import SoftwareLicenseServiceChangeLicensePlan
from beget_openapi_vps.paths.v1_vps_software_license.get import SoftwareLicenseServiceGetLicenseInfo


class SoftwareLicenseServiceApi(
    SoftwareLicenseServiceChangeLicensePlan,
    SoftwareLicenseServiceGetLicenseInfo,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
