# coding: utf-8

"""
    API Облачных серверов

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.7.7
    Generated by: https://openapi-generator.tech
"""

from beget_openapi_vps.paths.v1_vps_statistic_cpu_id.get import StatisticServiceGetCpu
from beget_openapi_vps.paths.v1_vps_statistic_cpu_details_id.get import StatisticServiceGetCpuDetails
from beget_openapi_vps.paths.v1_vps_statistic_disk_id.get import StatisticServiceGetDisk
from beget_openapi_vps.paths.v1_vps_statistic_disk_usage_id.get import StatisticServiceGetDiskUsage
from beget_openapi_vps.paths.v1_vps_statistic_load_average_id.get import StatisticServiceGetLoadAverage
from beget_openapi_vps.paths.v1_vps_statistic_memory_id.get import StatisticServiceGetMemory
from beget_openapi_vps.paths.v1_vps_statistic_network_id.get import StatisticServiceGetNetwork
from beget_openapi_vps.paths.v1_vps_statistic_processes_id.get import StatisticServiceGetProcessList


class StatisticServiceApi(
    StatisticServiceGetCpu,
    StatisticServiceGetCpuDetails,
    StatisticServiceGetDisk,
    StatisticServiceGetDiskUsage,
    StatisticServiceGetLoadAverage,
    StatisticServiceGetMemory,
    StatisticServiceGetNetwork,
    StatisticServiceGetProcessList,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
